[build]
builder = "nixpacks"
buildCommand = "npm install --no-cache"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1